name: Make Post

on:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create Post
      uses: actions/checkout@v2
      run: |-
        cd programs
        ./post.sh
