name: Make Post

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Create Post
      run: |-
        cd programs
        ./post.sh
